### PR TITLE
fix #8 - add `--include` and `--exclude` options

### LINKED ISSUE #8: Feature Request: Ability to specify a list of files (with wildcard match) to ignore
Many of our projects have a few files that always contain high entropy strings like SHA1 hashes or Base64 encoded values.  It would be nice to provide a list of files to be be ignored, sort of like a .gitignore file.

### PR DESCRIPTION
**Pull request by milo-minderbinder**
Fixes issue #8 by adding `--include_paths` and `--exclude_paths` options that allow the user to limit scanning to a subset of objects in the Git history by defining regular expressions (one per line) in a file to match the targeted object paths.

If provided, the `--include_paths` option should point to a file with regular expressions (one per line), at least one of which must match a Git object path in order for it to be scanned. If empty or not provided (default), all Git object paths are included (unless otherwise excluded via the --exclude_paths option).

Likewise, the `--exclude_paths` option, when provided, should point to a file with regular expressions, _none_ of which may match a Git object path in order for it to be scanned. If empty or not provided (default), no Git object paths are excluded (unless effectively excluded via the --include_paths option).

In either file, lines starting with "#" are treated as comments and are ignored.

### CODE REVIEW

**Comment by milo-minderbinder** [comment]
I realize this provides some duplicate functionality with #16 and #46, but since it _also_ adds additional capabilities with `--include` option, and also provides additional detailed documentation (and is based on current master & without merge conflicts currently), I figured it was worth a separate PR.

**Comment by dxa4481** [comment]
Hey @milo-minderbinder thanks for this PR. Would you mind adding some tests and examples to the tests.py script?

**Comment by milo-minderbinder** [comment]
No problem, thanks for a useful tool. And sure thing, I’ll add some tests as soon as I get a chance.

**Comment by milo-minderbinder** [comment]
@dxa4481 done. let me know what you think

**Comment by milo-minderbinder** [comment]
@dxa4481 I fixed the merge conflicts after seeing @sobolevn question. If you're not interested in this PR though, just let me know and I won't worry about fixing future conflicts and/or close the PR.

**Comment by dxa4481** [comment]
Hi @milo-minderbinder I haven't forgotten about this PR.

The thing is I just added support for custom rules being sourced from a json file, and I think it makes more sense to just have one settings file, which your includes and excludes can also take part in.

It's been laziness mostly, but the vision I have is, one json config settings file you can pass which will include both custom rules and includes and excludes.

I'll sit down hopefully this weekend or next and bang it out.

Thanks for being patient.

**Comment by milo-minderbinder** [comment]
@dxa4481 No problem. So, to clarify, since this PR is now in conflict again and what you're describing would require either reworking this PR to use the JSON rules file as you've just described or closing this PR and starting from scratch, what do you want me to do? I can start trying to implement what you've described, but obviously don't want to go through that effort if you'd rather control the implementation yourself. It's your project, so either way you want to handle it is fine, just let me know. Thanks!

**Comment by dxa4481** [comment]
I can take care of it. I'll make sure when I do I merge in your change set so you get credit.

**Comment by samuelhwilliams** [comment]
Did this go anywhere? Would be useful to be able to exclude files (e.g. node modules/package.json).

**Comment by adrianbn** [comment]
This would have come in handy for a colleague today too. Is there anything I can do to help move this along?

**Comment by Demuxx** [comment]
Any thoughts on merging this?

**Comment by dxa4481** [comment]
Hi everyone, this has been on my todo list for a while. My focus right now is on a Kiwicon presentation, but when that's done, I promise to prioritize this feature.

**Comment by poblahblahblah** [comment]
Would love to see this feature merged. How did Kiwicon go?

**Comment by maniankara** [comment]
+1

**Comment by rahiparikh** [comment]
@milo-minderbinder Thanks for the PR and @dxa4481 for supporting the awesome tool. Would it be possible to merge the PR? It has great potential of helping the community.

**Comment by silasbw** [comment]
@dxa4481 we (@godaddy) would like to use trufflehog in our CICD pipelines.  In order for that to work well for us, we need the ability to manually suppress false positives.  Excluding certain files addresses a large percentage of false positives we are currently seeing (*e.g.*, excluding self-signed development certs).

Can we help move this issue along?  One thing we could do is spec out the work required for https://github.com/dxa4481/truffleHog/pull/66#issuecomment-361276510 (*i.e.*, submit an issue to this repository with specific proposals on how to do that work/refactoring). Would that be helpful?

**Comment by dxa4481** [comment]
I'll see if I have some time this weekend

**Comment by dxa4481** [comment]
Apologies for not getting to it sooner. Took a bit of work because of all the merge conflicts (because I took so long to merge it) but it's merged in and shipped to pypi.

**Pull request merged**
