### PR TITLE
Fixed since_commit and tests

### PR DESCRIPTION
**Pull request by dmrickert**
Fixes broken since_commit referenced in #218 

The break is also obvious if you look at the git log and the hashes the since_commit tests were looking for.  There was a commit that should've been found sooner, and it should've been found in all 3 current branches.

### CODE REVIEW

**Comment by cristianbriscaru** [comment]
Any progress on this? 
We are experiencing the same issue

**Comment by dxa4481** [comment]
I'll try to take a look this weekend

**Comment by salimane** [comment]
@dxa4481 a new release on pip would be welcomed

**Comment by dxa4481** [comment]
Hey @salimane I cut a release on February 4th, 2.2.1, are you having issues with that release?

**Comment by salimane** [comment]
`0f223225d6efc8c64504d9381eececb06b14c0e6` is the last commit on `https://github.com/dxa4481/truffleHog`

If I run the following command
```
truffleHog --regex --entropy=False --since_commit=0f223225d6efc8c64504d9381eececb06b14c0e6 https://github.com/dxa4481/truffleHog
```

I will expect no warnings but it still scans the full commit history.

**Comment by dxa4481** [comment]
@salimane so trufflehog scans all branches, and looks for the since_commit in each branch it scans. Since the latest commit (in dev) isn't in the other branches, it still does a full scan of those https://github.com/dxa4481/truffleHog/blob/dev/truffleHog/truffleHog.py#L339

To get around this you can provide the branch flag to keep it only scanning a single branch.

I think that's it. Let me know if you find anything else wonky with it.

**Comment by salimane** [comment]
@dxa4481 thanks. I have added the branch flag and it worked.

**Pull request merged**
