### PR TITLE
Update regexChecks.py

### PR DESCRIPTION
**Pull request by carnal0wnage**
added a few regex additions.  The ones with *[\'|"]  weren't working for me but i didnt remove them i just created some additional ones that did work for me

i created a repo with fake secrets to test

https://github.com/carnal0wnage/fake_commited_secrets

### CODE REVIEW

**Comment by dxa4481** [comment]
I've merged the new ones, thanks for the additions. The ['|"] part ensures that the secret is rapped in quotes. This is to improve signal. A simple example with one of your newer ones, a github URL would likely flag on [g|G][i|I][t|T][h|H][u|U][b|B].*[0-9a-zA-Z]{35,40} such as https://github.com/google/googletest/commit/10ef1d9a1e7e6a0b3701d262cf1b889620fdbbc9

To prevent this URL from flagging, we ensure only secrets rapped in quotes will flag. This means we'll miss out on some real secrets, but we increase our signal to noise ratio in doing so.

**Comment by carnal0wnage** [comment]
thanks for the explanation on the ['|"] part.  I dont see secrets wrapped in "" too frequently myself.  All the ones in that fake repo are ones i found on github or pastebin and they werent matching.  I appreciate the merge of the others!

**Comment by dxa4481** [comment]
If you can find another way to catch those secrets without increasing noise too much, I'll merge it. Maybe make sure the string is wrapped by an equals or a colon on the left and a newline on the right?

**Comment by carnal0wnage** [comment]
cool. if i find a better way i'll do a PR / issue / or an email.

thanks!

**Comment by dxa4481** [comment]
@carnal0wnage 👋

**Pull request merged**
